# Due to Wi-Fi chip was not working we decided to use the KV260 that we also had at our disposal in order to create a custom app
# This script is based on the project *Creating a Custom Kria App* by *albertabeef (Mario Bergeron)*:
# https://community.element14.com/technologies/fpga-group/b/blog/posts/kv260-vvas-sms-2021-1-part7

# First we need to flash the image to the SD card
# Link to download
# http://avnet.me/kv260-vvas-sms-2021-1-prebuilt

# File downloaded:
# kv260-vvas-sms-2021-1-prebuilt-20220110.zip

# Folder uncompressed:
# kv260-vvas-sms-2021-1-prebuilt-20220110

# Folder with images:
# kv260-vvas-sms-2021-1-prebuilt

# Uncompress
# ./sdimage7kv260-vvas-sms-2021-1-sdimage

# Copy with balena
# petalinux-sdimage.wic

# Resize with 'Disks'

# Start kv260 with the SD card with the image

# user : petalinux
# password : root

# We configure Ethernet in order to install the packages needed

rm /etc/resolv.conf

echo '# Generated by Connection Manager' > /etc/resolv.conf
echo '' > /etc/resolv.conf
echo 'nameserver 84.88.62.194' >> /etc/resolv.conf
echo 'nameserver 84.88.62.220' >> /etc/resolv.conf

ifdown eth0

sudo ip addr flush dev eth0
sudo ip addr add 10.1.2.198/24 dev eth0 label eth0
sudo ip route add default via 10.1.2.1 dev eth0
sudo ip link set eth0 up

# We make a brief check to see if Internet works:
ping -c 3 www.google.es

cd /home/petalinux/
mkdir rpm

# From host:
scp ~/Downloads/kv260-vvas-sms-2021-1-prebuilt-20220110/kv260-vvas-sms-2021-1-prebuilt/rpm/* petalinux@10.1.2.198:/home/petalinux/rpm

# From kv260:
cd rpm

sudo su -l root

dnf install kv260-vvas-sms-1.0-r0.0.zynqmp_generic.rpm
dnf install kv260-vvas-sms-models-1.0-r0.0.cortexa72_cortexa53.rpm
dnf install kv260-vvas-sms-app-1.0-r0.0.cortexa72_cortexa53.rpm
dnf install packagegroup-kv260-vvas-sms-1.0-r0.0.noarch.rpm

echo firmware: /lib/firmware/xilinx/kv260-vvas-sms/kv260-vvas-sms.xclbin > /etc/vart.conf

# Checking if accelerators are installed:
xmutil listapps

# Unload this app:
xmutil unloadapp kv260-dp

# to load:
xmutil loadapp kv260-vvas-sms

# We go to the directory containing apps
cd /opt/avnet/kv260-vvas-sms/app

# Configure monitor (we will see that the monitor powers on with diagonals of diferent colors) 
source ./setup.sh

# "ctrl + c" to stop the monitor

# Execute the app:
./smart_model_select

# You will see on the monitor possible options
# To select them we need to introduce on the host a series of 4 numbers:
# 1: Source of the signal
# 2: Type of application to execute
# 3: Select output: File (1), Nothing/fake (2) or Monitor (3)
# 4: Measure performance. Do not measure (0), Measure (1). We recommend that in this option only use '0' 

# Writing "3,15,3,0": Facial recognition using USB camera 
# Using minicam MIPI: 4,13,3,0
# 3,11,3,0: Body recognition
# 3,3,1,0: Output video (output.nv12)

# On host to see the output:
scp petalinux@10.1.2.198:/opt/avnet/kv260-vvas-sms/app/output.nv12
