echo 'ifdown eth0' > config_eth0.sh

echo 'sudo ip addr flush dev eth0' >> config_eth0.sh

echo 'ifup eth0' >> config_eth0.sh

chmod +x config_eth0.sh 

./config_eth0.sh 

rm /etc/resolv.conf

echo '# Generated by Connection Manager' > /etc/resolv.conf
echo '' > /etc/resolv.conf
echo 'nameserver 84.88.62.194' >> /etc/resolv.conf
echo 'nameserver 84.88.62.220' >> /etc/resolv.conf

ping -c 3 www.google.es
